<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'product_name' => 'Sillon Frailero',
                'product_details' => 'The Butaca, a hybrid of Spanish design and Filipino craftsmanship, was used by Dr. José Rizal and Ilustrado families. Known for its broad arms and rattan seat, it symbolized intellect and pride.',
                'product_image' => 'SillonFraillero.png',
                'sold_as' => 'piece',
                'weight' => '15kg',
                'size' => 'Large',
                'composition' => 'Wood and Rattan',
                'color' => 'Dark Brown',
                'location' => 'Manila',
                'issues' => null,
                'original_price' => 12000.00,
                'retail_price' => 14500.00,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'category_id' => 1,
            ],
            [
                'product_name' => 'The Dulang',
                'product_details' => 'A low wooden table used by Aguinaldo and Katipuneros for meals and planning. A symbol of unity and simplicity.',
                'product_image' => 'TheDulang.png',
                'sold_as' => 'piece',
                'weight' => '10kg',
                'size' => 'Medium',
                'composition' => 'Molave Wood',
                'color' => 'Natural Wood',
                'location' => 'Cavite',
                'issues' => null,
                'original_price' => 8000.00,
                'retail_price' => 9500.00,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'category_id' => 1,
            ],
            [
                'product_name' => 'The Aparador',
                'product_details' => 'Heirloom narra wardrobe owned by Doña Narcisa Rizal. Carved from narra and molave, it reflects the grandeur of Vigan and Taal homes.',
                'product_image' => 'TheAparador.png',
                'sold_as' => 'piece',
                'weight' => '60kg',
                'size' => 'XL',
                'composition' => 'Narra and Molave',
                'color' => 'Mahogany',
                'location' => 'Vigan',
                'issues' => null,
                'original_price' => 20000.00,
                'retail_price' => 24000.00,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'category_id' => 1,
            ],
            [
                'product_name' => 'The Fisherwoman by Vicente Manansala',
                'product_details' => 'Cubist masterpiece said to be inspired by Manansala’s mother. A tribute to resilience and beauty in simplicity.',
                'product_image' => 'TheFisherWoman.png',
                'sold_as' => 'piece',
                'weight' => '2kg',
                'size' => 'Medium',
                'composition' => 'Oil on canvas',
                'color' => 'Multicolor',
                'location' => 'Gallery',
                'issues' => null,
                'original_price' => 30000.00,
                'retail_price' => 40000.00,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'category_id' => 2,
            ],
            [
                'product_name' => 'The Sphinx of the Desert by Jean-Léon Gérôme',
                'product_details' => 'An Orientalist artwork capturing the mystique of ancient Egypt. Inspired by the artist’s travels and symbolizing lost wisdom.',
                'product_image' => 'TheSphinxoftheDesert.png',
                'sold_as' => 'piece',
                'weight' => '3kg',
                'size' => 'Large',
                'composition' => 'Oil on canvas',
                'color' => 'Warm Tones',
                'location' => 'Gallery',
                'issues' => null,
                'original_price' => 40000.00,
                'retail_price' => 50000.00,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'category_id' => 2,
            ],
            [
                'product_name' => 'The Moonlit Night by Edgar Degas',
                'product_details' => 'Rare night scene painted by Degas, showcasing moonlit cityscapes and quiet beauty. Inspired by Montmartre walks.',
                'product_image' => 'MoonlitNight.png',
                'sold_as' => 'piece',
                'weight' => '2.5kg',
                'size' => 'Medium',
                'composition' => 'Oil on canvas',
                'color' => 'Blue-Grey',
                'location' => 'Gallery',
                'issues' => null,
                'original_price' => 38000.00,
                'retail_price' => 47000.00,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'category_id' => 2,
            ],
            [
                'product_name' => 'Victorian Silver Teapot',
                'product_details' => 'Antique teapot used by Queen Victoria, representing British refinement. Floral motifs and sterling silver craftsmanship.',
                'product_image' => 'VictorianSilverTeapot.png',
                'sold_as' => 'piece',
                'weight' => '1.2kg',
                'size' => 'Small',
                'composition' => 'Sterling Silver',
                'color' => 'Silver',
                'location' => 'UK Antiques',
                'issues' => null,
                'original_price' => 15000.00,
                'retail_price' => 18000.00,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'category_id' => 3,
            ],
            [
                'product_name' => 'Antique Italian Bread Warmer',
                'product_details' => 'Renaissance-era ceramic warmer used in noble Tuscan homes. Symbol of warmth and hospitality.',
                'product_image' => 'Antique Italian Bread Warmer.png',
                'sold_as' => 'piece',
                'weight' => '2.8kg',
                'size' => 'Medium',
                'composition' => 'Ceramic',
                'color' => 'Terracotta',
                'location' => 'Tuscany',
                'issues' => null,
                'original_price' => 9500.00,
                'retail_price' => 11500.00,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'category_id' => 3,
            ],
            [
                'product_name' => 'Spanish Colonial Brass Cocoa Pot',
                'product_details' => 'Brass batirol used in Spanish-era Philippines for rich tsokolate. Favored by friars and officials post-Mass.',
                'product_image' => 'SpanishColonialBrassCocoa Pot.png',
                'sold_as' => 'piece',
                'weight' => '1.5kg',
                'size' => 'Small',
                'composition' => 'Brass',
                'color' => 'Gold',
                'location' => 'Philippines',
                'issues' => null,
                'original_price' => 6500.00,
                'retail_price' => 7900.00,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'category_id' => 3,
            ],
        ]);
    }
}
